### ISSUE TITLE
Impostor syndrome

### ISSUE THREAD

**Issue by Spharian** [rachsmithcodes/ama#1]
Hi Rachel,

A well known problem in this job is the famous impostor syndrome. My question is simple: have you ever felt like an impostor? If so, how do you deal with it? As a (web) developer, our colleagues are every persons in the world with a computer and an internet connection.

Thanks :)

**Comment by rachsmithcodes** [comment]
Hey Spharian,

Truthfully, I have feelings of "not being good enough" almost every day. Rather than let it stress me out,  I've learned to accept that it is a feeling I will never really be able to shake off. There are some strategies I use to stop the feelings of inadequacy from actually interfering with my work or life.

**1.** Accept there are things I do not know yet or can not do yet, and that is totally okay. No one can know everything! I tell myself to focus on the things that matter _right now_ and I can learn the other stuff when it is the right time.
**2.** Try not to compare myself to other people on the internet (this one is really tough, I am definitely prone to it). People often present the best version of themselves on the internet and you never really know their personal situation, how much spare time they have or the pressures they have in their life. You're doing yourself a disservice by comparing your progress to theirs. 
**3.** Sometimes I just like to mentally list out everything I've learned or approved apon, in say, the last 6 months. It might seem like a weird activity to list out your achievements to yourself like this but I really feel like it helps me gain perspective when I start beating myself up for not being good enough.

It's funny, some of the most driven and successful people I know actually constantly struggle with the feeling they aren't "good enough" yet. It is actually part of what drives them to progress so quickly in their chosen field. I think it is a totally normal feeling to have and as long as you aren't letting it hold you back (eg. stopping you from applying for that job you want) then it can be turned in to a positive thing :sparkles:
