### ISSUE TITLE
Your path to the States?

### ISSUE THREAD

**Issue by mitchbart** [rachsmithcodes/ama#10]
Hey Rachel,

Australian here, I'm always interested in hearing about the path other Aussies have taken to land dev jobs in the States and elsewhere. How'd you get your start? Did you do a lot of dev work in Aus before making the move? What's the market like over there for Australians?

Cheers,
Mitch

**Comment by rachsmithcodes** [comment]
heya Mitch! Always love to hear from fellow Aussies.
Personally, I never had any real aspirations to live and work in the States. My original plan was to move to London for 2 years and gain experience there before moving back to Australia.
However, shortly after I began my London stint a friend of mine from Australia happened to move to the USA and start his own agency (Active Theory) and when they were looking to hire someone they asked if I would be interested. The job included the opportunity to work on advertising projects that Australian brands just don't really offer so I thought "why not?" and moved to the States. In hindsight it was the best thing I could have done for my career, and I'm so glad I made the leap. 

Knowing one of the guys who hired me certainly helped in getting the gig but it was also due to the work experience I gained in the UK and Australia. I would definitely say you'd want to have a couple of years work experience before you attempt to land a job in the USA simply because you would be seen as a lower risk hire. That being said I've had more than one friend land US jobs immediately after graduating university - so its not impossible to be hired as a junior.
E3 Visas (the US Visa for temporary working Australians) are the easiest and cheapest to secure so companies (especially large ones) don't really see it as a barrier to hiring. If you have a bachelor's degree (required for the E3) and you put yourself out there I am sure you would be able to land a US job without too much difficulty - especially if you are willing to live in SF/SV, LA or New York. I have Australian friends who work/have worked for Microsoft, Facebook, Buzzfeed, Uber, Google, Adobe & other start ups so the jobs are definitely available and I would say the market is good!
