### ISSUE TITLE
Online Portfolio

### ISSUE THREAD

**Issue by blairwilcox** [rachsmithcodes/ama#12]
Hi Rachel,

As a developer, I was wondering what you consider important in an online portfolio? I've always been told to highlight write-ups of large projects, but I've noticed that many developers tend to put blog posts front-and-center. What's your opinion on this?

Thanks,
Ben Wilcox

P.S.
Great idea using GitHub issues as a platform for AMAs!

**Comment by rachsmithcodes** [comment]
Hiya Ben,

Personally I think it is great to have both examples and explanations of work you've done, as well as a bit of writing (if possible).

Examples of work do the obvious by proving what you are capable of and have achieved in the past. Writing blog posts however gives an insight to your personality and thought process, as well as demonstrates that you are good at communicating!

Writing/blogging is hard though so don't stress out if your portfolio doesn't have any, in my previous experience (all agency) employers were more concerned with the "previous work" part of things when they were checking out potential hires. I have written about some more portfolio tips [here](https://rachsmith.com/2015/portfolio-tips).

Another reason you might notice that developers put blogging front and center on their websites is because they are not actively looking for work, so their online presence is more of a place to just share with the community rather than promoting themselves to potential employers. This is what I use my site for and I have developer friends that do the same thing.

Hope that and the post I linked to above gives you some answers!
