### ISSUE TITLE
Learning JS

### ISSUE THREAD

**Issue by anonet1** [rachsmithcodes/ama#16]

**Comment by rachsmithcodes** [comment]
hi Aneta!
My personal experience with JavaScript was going from jQuery to vanilla JS. After that I learnt frameworks like react etc.
When I was learning JavaScript it was still only es5, and now there is es6/es2015 which complicates things a little for newcomers. I would suggest maybe sticking to es5 first and then after you feel comfortable with that you can look at the new syntax, as trying to process both at the same time might be tough when you're looking how to structure your code.
The resources I used most often when I was learning vanilla JS were from http://superherojs.com/ - I would try and build things using examples from the understanding your JavaScript and organizing your code sections until it stuck. Maybe you'll find something in there you find useful as well.
This is also great practice for when you feel like you've learned a few things: https://github.com/rmurphey/js-assessment

As for _what to begin with_ I feel like the best thing you can begin with is something that interests you. So try and build something with JavaScript that you find fun and appealing. In my case I loved animation so I would try and build things with canvas and structure my JavaScript for the canvas animations with different patterns so I could understand how to write better organized code. I also made a lot of DOM animation stuff and drag and drop interfaces because I was interested in browser events. You might have different interests but the important thing is to _just keep building_ and your bound to get better at JavaScript over time.

I hope that was helpful, best of luck with your learning!!
