### ISSUE TITLE
Where to Start next ?

### ISSUE THREAD

**Issue by omkarnath1123** [rachsmithcodes/ama#17]
Hi rachel
I'm 3rd year B.tech student after my graduation i want to become **web wizard like you**.I currently know HTML CSS3 JS/jQuery (approx intermediate stage) want to make cool projects and also want to work in company like CODEPEN. Any guidance  where should i look further to learn. also a personal question how to remember all the tags elements and styling & any further information to guide me to this field or make my resume better....
Sorry, but i have lots of questions for a Developer because i want to become a developer..
Please suggest link where i can fork project on github or watch them. Can you share your achievements till yet if you like. 
Link for my resume:- 
[qwe.docx](https://github.com/rachsmithcodes/ama/files/225670/qwe.docx)
Hope so, you will guide me.
Thanks in advance.

**Comment by rachsmithcodes** [comment]
Hi Omkar,

It sounds like you've gained some sound knowledge through your studies which is great. So I'm going to assume the best thing you can do now is use them as much as you can on building projects.

A lot of people worry/ask about what project they should build next, the only thing you need to worry about is building something _you are interested in and enjoy_ in order to keep going. Just start making projects. It can be anything you want. The important part is that you try to build something and then learn from the experience.

Work experience is also important. My first few jobs were not in any way as exciting as the one I have now at CodePen. I spent some years working on less exciting stuff, but that gave me the skills to get the job I have now. So sometimes, just taking any web developer job after university where you will be learning new things is great, even if it is just something you do for 6 months - a year. 

I did not follow any particular path to get to where I am now, I just kept trying to learn new things and kept building things that I was interested in making. I kept chasing better jobs and eventually I ended up to where I am now :) 

Also to answer your Question about _how to remember all the tags elements and styling_ I use Google a lot. I have to re-Google things all the time because I can't remember them - and thats okay :) eventually after you've repeated things a few times it starts to stick. So the main thing is to keep building and keep practicing. 

Best of luck!! You will do great
