### ISSUE TITLE
What should be the next step?

### ISSUE THREAD

**Issue by omkarnath1123** [rachsmithcodes/ama#19]
Hi Rachel,
I want some suggestions on from where i can practice more intuitive java-script Problems.
From where i can know about the new JS library which are hot in the market . 
If possible  Please provide the link in the reply .
Also i also make up my mind to learn the back end languages also .So, PHP and My-SQL is sufficient ?
- Thanks

**Comment by rachsmithcodes** [comment]
hi Omkar,

This is a great resource for JavaScript problems to practice: https://www.freecodecamp.com/map#Basic-Algorithm-Scripting.
https://www.codewars.com/ and https://www.hackerrank.com are other sites that provide coding challenges to solve.

For keeping up with newly released JS libraries, I tend to use https://frontendfront.com/ as a resource for front end links and news. There's also https://www.reddit.com/r/javascript if you can stand to be on reddit :)

As for backend languages, I would choose the one you think would best suit the needs of what you're trying to build or just whichever you like to use more. I've used PHP, Ruby, Python, Node.js languages, SQL and MongoDB databases. I like them all but I think Node.js is my favourite (because its JavaScript).

I hope that helps, cheers
