### ISSUE TITLE
Canvas and WebGL: where to start?

### ISSUE THREAD

**Issue by Spharian** [rachsmithcodes/ama#2]
Hi Rachel,

There are many **awesome** resources available to learn almost everything: HTML, CSS, Javascript, PHP, Ruby, etc... but where to start learning WebGL and "advanced" canvas things? There are many **interesting** resources, like ThreeJS, pixi js and easeljs but they seems much less developer friendly (always have the feeling that you need a strong math/3D background and animation skills to get into it).

Codepens are awesome but sometimes lacks clarity.

**Comment by rachsmithcodes** [comment]
hey Spharian,

So, the best book I've read with regard to understanding the math and physics behind animating with JavaScript is this one:
Foundation HTML5 Animation with JavaScript
<a href="http://www.amazon.com/Foundation-HTML5-Animation-JavaScript-Lamberta/dp/1430236655">Amazon Link</a>
I can not recommend it highly enough! It is an excellent book that you can use the learnings from and apply to Canvas or WebGL (or SVG even).

One of the tricky things to grok about WebGl is how the content pipeline works. A book that goes in to this in depth is this one: Programming 3D Applications with HTML5 and WebGL
<a href="http://www.amazon.com/Programming-Applications-HTML5-WebGL-Visualization/dp/1449362966">Amazon Link</a>

These resources cost money, compared to the free tutorials out there, but I've found that the depth of those free resources is lacking (possibly because all this web animation stuff is still fairly new and not very mainstream). So if you want more than just your "introduction to Three.js" type blog posts, books seem to be the way to go.

I would not call myself an advanced WebGL user at all, I more than often am just messing with the code my boss has already written at work! But I do have some friends who are very good at it and they all did it the hard way, just making a tonne of experiments and painstakingly piecing together bits of info about WebGL from the internet along the way. Maybe one day someone will write/make the perfect resource to guide people from beginner through to advanced in this subject :rainbow:. Right now I don't think that resource exists.

If you do decide to check out those books and make anything, make sure you send me what you make, I love to see what people make!
