### ISSUE TITLE
CodePen Features & Jobs

### ISSUE THREAD

**Issue by mrlubos** [rachsmithcodes/ama#22]
Hey Rach,

I've got 3 questions (had 2 but thought of another one while typing this, hopefully it won't increase again):

1) Are there any plans to add more social features to CodePen? One I frequently think of is being notified when people I follow at least post a new Pen. Has anyone else requested this?

2) This one is limited by the editor powering the CodePen editor I think, but anyway. Any plans to allow creating pens consisting of multiple files? I think CodeAcademy has this feature in their tutorials. Could be useful if the Pen outgrows its initial window.

3) How on Earth did you get to work with CodePen?! I don't see a Careers section on the page and when I asked last time on Twitter, I was only told that no places are available. So what is your story regarding this haha.

Thank you!

**Comment by rachsmithcodes** [comment]
hi Lubos,

1) We definitely want to make CodePen more social, and give people more reasons to make following others "worthwhile". Notifications like that could be a way to do this. We do get asked for such notifications/social features on occasion yeah. We're not actively working on it right now but making CodePen more social in this way is definitely part of our (big) vision for the product!

2) This is another part of our vision. I can't say when it will happen, but some day you'll be able to do this on CodePen.

3) So CodePen is a very small company, before Marie, Jake, Tim H and I joined there was only the 3 founders. They received some funding last year to hire a small staff. At that time the founders asked me if I would be interested in joining (I was an active user) as they were looking for a front end engineer with my skills. So I was just in the right place at the right time basically. I'm guessing they won't be able to hire again for a while because we have to become profitable using the funding they were given before the company can afford to do that.

Cheers!

Rach

**Comment by mrlubos** [comment]
Thank you, makes sense. I was thinking it was due to CodePen being a small company, but wanted to confirm. I will let you know if I have more questions haha!
