### ISSUE TITLE
Companies to look at

### ISSUE THREAD

**Issue by garyyau** [rachsmithcodes/ama#24]
Hello Rachel!

I came across your work from your appearance on the Versioning show (the first one I've listened to) and I was really interested in what you do. I graduated with a Computing Science major around 3 years ago, and decided a few months ago that I wanted to focus on becoming a Frontend Developer. Like you, I have a _slight_ design background, but essentially I do enjoy design and all the things it brings with coding, which was why I wanted to become a Frontend Developer and my interest in your work.

Right now, I'm in a place where I'm not really sure what type of companies I should look into finding jobs for in which to really build up experience in building great design and user experience frontend layouts. I recall from the show that you worked at an advertisement agency, so would you say those types of companies would help the most? I'd appreciate even actual company names for me to look into.

Thanks!

**Comment by rachsmithcodes** [comment]
hi Gary,

Speaking purely from the experience I had, I think working in an agency environment is a really great way to quickly upskill in front end work. The things that made agency work distinct from my experience working for a product were:
-  short deadlines, and having to solve problems very quickly (a great skill to have as a dev)
-  constantly working on different projects, means you're not staring at the same design or codebase too long
-  a lot of autonomy w/ regard to the code solutions I used, even very early on my career
-  inheriting and updating a lot of legacy code, some would see this as a bad thing but having to read and use past developer's code actually helped me learn a lot about JavaScript

There were a few parts that I didn't like so much (not every agency is like this but it was a common thread in the places I worked)
-  the expectation to work long hours to meet deadlines (although I didn't mind this so much when I was younger)
-  very little developer organization and process (no git branching model, hair-raising deployment processes, codebases that would fall apart at the slightest change because they'd been built so quickly)
-  sometimes you'd just have to build what the client wanted even if what they wanted was ridiculous and/or terrible.

I wouldn't trade my agency experience for anything. As for which ones you should look in to, I would just do some googling around and check out the portfolios of agencies in your area (or whichever area you want to live in). Check out the past client work and see if its something you would like to make that sort of thing in your career. For example, I really liked the highly animated, campaign site work in digital advertising so I was chasing work that could help me end up at a place like Media Monks, Resn or Active Theory (where I ended up working). If digital advertising agency work appeals to you may I suggest you check out https://thefwa.com/, http://www.awwwards.com/ and look up the agencies who's work you like on there. 

Ad agencies aren't the only kind of digital shops to work for though. If less campaign-y and more legitimate business sites appeal to you as a developer you might want to check out agencies that resemble Sparkbox, Made by Many or Filament Group.

Best of luck with your career, whether you choose to pursue agency work or not! cheers

**Comment by garyyau** [comment]
Thanks for the response! I took a quick look at some of the places you recommended, and I really love the work that Active theory does.
