### ISSUE TITLE
Animated Header Background

### ISSUE THREAD

**Issue by BigBadBill** [rachsmithcodes/ama#26]
Greetings:

I'm trying to add a line of links under the <h1> header in the index file so I can kill the empty space and keep people from being confused. However, when I do it doesn't show up. When I encompassed it within the <h1> tag all the bad things you could possibly imagine happening happened. I've gone slightly blind wandering through the CSS files but I don't see any limitations on the amount of text that can be used. Can you tell me what I'm doing wrong?

Bill

**Comment by rachsmithcodes** [comment]
Hi Bill,

its not easy for me to tell whats happening if I can't see your code and I generally don't give personal troubleshooting help with articles I've written but to give a hint, I added a list of links in an example here:

http://codepen.io/rachsmith/pen/12bb12601140840ca887b1327cac6741

In order to add links you'll need to add some HTML (I used a `<ul>` with some `<li>`s) and then some CSS to style the new HTML

Good luck!

**Comment by BigBadBill** [comment]
Hi Rachel:

That was exactly what I needed. Thanks. And, just FYI, the reason I  
asked was because your bio at GitHub says "ask me anything" and I  
really wasn't interested in whether you liked tacos or dated  
ex-bikers. This was the only question I had.

Thanks again for all your help. I wish you nothing but the best.

Bill

Quoting Rachel Smith notifications@github.com:

**Comment by BigBadBill** [comment]
Hi Rachel:

I wanted to thank you for your help and let you check out what I did  
with your background. All things considered I htink it came out pretty  
cool.

http://BillMcSciFi.com

Bill McCormick

**Comment by rachsmithcodes** [comment]
Hi Bill, nicely done!
