### ISSUE TITLE
5 Questions for Web Developers/Designers/etc

### ISSUE THREAD

**Issue by jaymiejones86** [rachsmithcodes/ama#29]
I have a podcast called Coder Catchup which you can find at http://codercatchup.com/ or on twitter https://twitter.com/codercatchup and I am approaching Episode 100 of the weekly podcast series I am doing.

The podcast is about spreading information to anyone who works on the web, things that may hopefully improve their career or open up other opportunities or thought processes.

For episode 100 I am seeking out various people in the web community and asking if they would mind answering 5 question that will be read out on the episode.

Would you mind answering these questions for me?

- If you were starting fresh, what would you primarily focus on? (e.g. as a new web designer/developer)
- What is one piece of advice you think is most important for web developers/designers going forward?
- What would you do to get out of a slump or plateau with your web career?
- What is 1 thing you would like to see web developers/designers doing more of?
- One piece of advice of your choosing

**Comment by rachsmithcodes** [comment]
Hi Jaymie,

I see you've already made your episode 100, sorry I couldn't get back to you soon enough. Congrats on the 100 episodes!

**Comment by jaymiejones86** [comment]
Hi!

Yes unfortunately the episode has been recorded and aired and I missed out on your answers.
Due to the response of the episode, I am looking at doing more episodes like this and wonder if you would still be interested in answer the above questions for a stand alone episode, or even potentially for an interview on the podcast?

Let me know your thoughts.

**Comment by rachsmithcodes** [comment]
Hi again Jaymie,

I listened to some of codercatchup, and realised you are a fellow Aussie!

I can attempt to answer your questions, although the longer I'm around and doing this stuff the less qualified I feel to give people advice, because everyone's circumstances are different, and it seems presumptuous to assume what works/ has worked for me will work for other people. So I'll answer your last question first:

**One piece of advice of your choosing**
As developers, it can be very tempting to get caught up in comparing yourself to everyone else, and either stressing over the fact you're not keeping up, or stressing over the fact other people aren't doing things the way you think they should be done. As long as you're learning (at your own pace), treating people well and keeping an open mind, you'll do very well in this industry.

**If you were starting fresh, what would you primarily focus on? (e.g. as a new web designer/developer)**
If I was starting fresh when I started in 2011, I honestly would repeat what I did (Flash, followed by WordPress). I have no regrets about the early days of my career. If I was starting fresh in 2017 I would focus on getting very comfortable with JavaScript, as it is my favourite language and there are many exciting career opportunities for JS developers.

**What is one piece of advice you think is most important for web developers/designers going forward?**
Learn how you best learn. People have told me that I am "quick" or "clever" because I pick up new concepts reasonably fast but there is really nothing special about me except I have had several years to figure out how I best learn how to code. For me it is to do a little reading and then dive right in and hack at code I have little understanding of until I piece it together. For you it may be a totally different strategy. Ignore generic advice about 'do X first before you learn Y'. Put in the time to figure out how you best learn, and your rate of progress will dramatically improve.

**What would you do to get out of a slump or plateau with your web career?**
I've left every job I had before CodePen, almost as soon as I felt I had got to a point where I wasn't learning anything new. So I guess that's a way to avoid a plateau. I was contracting and working in agencies then so it was reasonably easy to hop from job to job as I progressed. I've only been at CodePen for a year so there has been plenty for me to learn still, if I reach a day where I feel like I'm not progressing in my day job I would probably turn to learning new things outside of work to avoid feeling like I'm in a plateau. But honestly I've always been extremely lucky and had more advanced/exciting opportunities become available.

**What is 1 thing you would like to see web developers/designers doing more of?**
Coming out of the web dev/design bubble and realising there are an array of human experiences so different to ours, and we have to be open to learning about them if we want to design and build good products. I would like us to take ourselves a little less seriously, and be kinder to each other. (That's like 3 things oops but w/e)

If you'd like to use my answers in one of your eps feel free, or I'd be more than happy to chat with you for the podcast. You can email me at contact@rachsmith.com if you want to talk specifics about scheduling :) Thanks!

/ @jaymiejones86
