### ISSUE TITLE
How did you start coding?

### ISSUE THREAD

**Issue by Jcook894** [rachsmithcodes/ama#37]
I would love to know how you started coding and why? And what kind of frameworks you like using? I love your work! cant wait to see what you come up with next!

**Comment by rachsmithcodes** [comment]
Hi Julian,

The very first time I started coding was in one of my high school senior classes. I can't remember what we used but I really liked it. That made me want to do a degree in Software Engineering so I went to university to study it but ended up changing my course and quitting coding for some years because I didn't have a good experience in that course. When I was 23 I wasn't really happy with my job/life so I decided to pursue coding again and discovered Front End development and was hooked from then on.
My favourite framework at the moment is React, we use it at CodePen and I really enjoy it! Thanks for asking a question and sorry it took so long for me to answer.

Cheers!
