### ISSUE TITLE
What to put first ? School or coding ?

### ISSUE THREAD

**Issue by abhisack** [rachsmithcodes/ama#4]

**Comment by rachsmithcodes** [comment]
Hi @abhisack!
Sorry it took me a while to answer this, I've been working a lot :)

Firstly, I think its great that you enjoy coding at such a young age! I didn't really have the patience for it when I was your age :) 
I think when it comes to school and the priority you give it, it really depends on whether getting good grades will help you achieve what you want from your life further down the road. From my experience, I think working hard at school work was beneficial for me because it allowed me to get a University degree that I could then use to get a good job. Although some of the stuff I learnt at school hasn't been super helpful to me later on, getting the good grades and getting the degree really did.
I do however have developer friends who didn't do so great at school and they still have have really great careers. So school isn't necessarily the only way to do well as a developer.

The thing to remember is that what you decide to do at this time is not irreversable, so even if you choose to focus energy on school now you can work on coding later. Or if you were to de-prioritise school now you could redo studies later (although that might cost a bit of time and money). The fact that you care about this shows you are bright and you're thinking about your future. So I think as long as you aren't completely ignoring your studies, and keeping in mind the opportunities available to you depending on how well you do in school, you'll be fine :)

**Comment by abhisack** [comment]
Thanks a lot for taking your time to clear my confusion. Now I'm really feeling better to take the decisions. Your advice will surely be helpful for me (just as your pens & posts are :) )
