### ISSUE TITLE
Does JavaScript get easier? 

### ISSUE THREAD

**Issue by kmshub** [rachsmithcodes/ama#5]
How long did it take you to fully grasp JS? I've been working on an Ember app for a few months now, with little improvement. Am I just a slow learner or is this something some people initially struggle with?  Rather, did you specifically struggle with JavaScript at all and/or how long did it take to overcome it, for lack of a better word.

**Comment by rachsmithcodes** [comment]
heya @kmshub 
Great question. I would say it took me about 3 years to really get my head around JavaScript. I spent a couple of years writing jQuery and not really improving my understanding of JS. I then spent a year of _concentrated effort_ on getting better at JS. I would only take on JavaScript heavy jobs and started writing vanilla JS - I also didn't spend much time on improving my CSS that year. I blogged about it here: https://rachsmith.com/2014/2013-the-year-of-javascript.html. Since then I've just been getting better by writing a lot of JavaScript in my day job, and on CodePen for fun :)

So to answer your questions, yes it does get easier! But it does take time and practice. You say you've been working with Ember for a few months? You are definitely not a slow learner. When I think about the time it would have taken me to write something I can do now in 5 minutes, back in the first year I was learning JavaScript - it could have been hours. 

Here's a couple of things I did to get better, faster.
- use vanilla JavaScript. Try to write anything with JS, outside of your Ember framework.
- read and attempt to understand other people's JavaScript. Read lots of different people's JavaScript because they'll use different styles. I was lucky to do this on the job via contracting but github's a great place to find lots of JavaScript projects. You could even try to read and understand the source code of Ember.
- Make an effort to study up on objects, context, prototype inheritence - the Understanding JavaScript resources from http://superherojs.com were really helpful

Some of this stuff won't necessarily help you build your Ember app faster, but I found I had to take a step back from the work I was ploughing through and spend some time to try to get a deeper understanding of the language. After repeated learning and the applying the learning to your actual work, things will start connecting in your brain and you'll begin to understand _how_ and _why_ Ember works and that part is magical. Good luck and be easy on yourself!!

**Comment by kmshub** [comment]
Thank you so much for your feedback and for the resources! Also, your confidence. It is good to hear that things will get easier with practice and determination. I am surrounded by people that know what they are doing, so it is easy for me to lose patience with myself. 
I really appreciate you taking your time to answer :)
