### ISSUE TITLE
Hi Rachel! Do you storyboard for your pens or web projects? If so, how?

### ISSUE THREAD

**Issue by sdras** [rachsmithcodes/ama#8]

**Comment by rachsmithcodes** [comment]
hey Sarah!! so you've uncovered my secret shame - I pretty much never storyboard! The reason for this is because I studied a degree in Creative Media that had some compulsory courses in film and cartooning. So I had to do these assignments where I would have to (badly) draw out pane after pane of "story" and then would be given a C on that assignment because of my crap drawing skills (they always said drawing skills shouldn't matter, but they did). I had no aspirations to go in to film and didn't like getting average marks so I found this activity _exceedingly tedious_ - so now even the word storyboard makes me shudder. I know this is a totally unreasonable attitude to have as storyboarding for UI animation is totally different and a totally worthwhile communication tool - so I'm working to shake my negative attitude haha.
At Active Theory we preferred the "interpretive dance" method, which you may be familiar with, in which you describe the motion with words and sound effects while wildly waving your hands around :grin: less effective than storyboarding but a whole lot more fun. Often we'd just go straight in to banging up some prototype code if we needed to communicate further, very very occasionally we'd pull a pen and paper out to scribble something resembling a storyboard.

My pens are almost never planned, more the result of iterative fiddling that stemmed from an original idea or inspiration. The planning/storyboarding part takes the fun out for me - though I recognise its pretty much necessary when working on complex commercial work.

Sorry if my anti-storyboard confession was not helpful :laughing:

**Comment by sdras** [comment]
Haha I don't think you should feel bad about doing it a different way (I also explain animations with my hands and sound effect noises with my mouth).  I typically tell people they don't need to make storyboards beautiful, mine are straight up hideous. But sounds like you earned some PTSD in school. Thanks for the answer! Super interesting.
