### ISSUE TITLE
Hi! Why is finding remote work so hard? 🤔

### ISSUE THREAD

**Issue by vollervidez** [rachsmithcodes/ama#9]
Hi!!!
This is something I'm dealing with right now. I currently work for a city government my first "professional" web developer position been here going on 6 months. But I'm starting to hate my job since I'm the youngest in the department by at least 10 years you can imagine how I get treated. I love what I do just not where I'm doing it at and the people above me. I want to get out before I start hating what I love to do.

I want to work with like minded people i want to work in a team not be the Lone Ranger. I want to be creatively criticized not put down.

So I've been applying to many web developer / front-end positions but always get the same old your good just not good enough for us even for entry/junior level positions. I always send my resume and website link (victorollervidez.com) with recent project examples but still no luck 😑. (Just started putting together my new site this past weekend so it is a bit incomplete)

Is there a trick to landing a remote position? 

I'm asking about remote because where I live web developers are practically non existent and not in demand for some reason.

Thank You 
~Victor

**Comment by rachsmithcodes** [comment]
Heya Victor!

I totally sympathize with your position. I also lived in a smaller city with not as many work opportunities when I was junior and had to self-teach on my first job as I was the only developer at the company. A position where you can grow and learn from others would certainly be more ideal and I can see why you would crave that!

So, to answer your question - why is finding remote work so hard? The reason companies are so reluctant to hire juniors for remote roles is because generally people at your stage of their career require help and mentorship to level up, and a lot of companies feel they can't facilitate that in a remote work environment. There is something to be said for having people physically in the room with you when you're likely to be asking a lot of questions (which is what all good juniors should be doing :smile: ).
Also - remote work requires a lot of self motivation and the ability to organize yourself. I don't doubt you have these skills! It is just hard for companies to believe you have them when you have less work experience - so remote hires are (generally) people who have at least a couple of years experience "proving" their work ethic.

That is not to say junior remote roles don't exist, and I think if you really want one you should just keep trying, keep building your portfolio with evidence that you can self organize and self motivate (perhaps a side project that you create on your own?) - and eventually you will get a job. My read of the market is that over time more and more remote jobs will become available - we just have to wait for companies to catch up to the 21st century :wink: 

Another option (and the one I took after my first 8 months of working) is to move to a city where there is a lot more opportunities available in the sort of work you want to do. Moving cities is no easy thing to do though and I understand if thats not possible, its just something to think about.

I wish you luck in your career!! Try not to lose heart - if you keep trying I am sure you will find a job you like.
